title: SHAHOOR TECH
author: Dilpreet Singh
email: dilpreet.shtech@outlook.com
description: > # this means to ignore newlines until "baseurl:"

Our innovators make applications to make you
     love your smartphones even more.

Welcome to Shahoor Technology
-----------------------------
We are working hard everyday to start serving you soon and will not compromise on
quality in order to launch soon. Stay in loop and keep watching this space for updates.
 
# social links
twitter_username: dilpreetsingh95 # DO NOT include the @ character, or else the build will fail!
github_username:  dilpreetshtech # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
